/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 parrot.glb
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/parrot.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Object_0" geometry={nodes.Object_0.geometry} material={materials.Material_0_COLOR_0} morphTargetDictionary={nodes.Object_0.morphTargetDictionary} morphTargetInfluences={nodes.Object_0.morphTargetInfluences} rotation={[Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/parrot.glb')
